<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-04T01:34:19 IST" name="Suite" finished-at="2024-01-04T01:35:34 IST" duration-ms="74381">
    <groups>
    </groups>
    <test started-at="2024-01-04T01:34:19 IST" name="Test" finished-at="2024-01-04T01:35:34 IST" duration-ms="74381">
      <class name="listeners.ListenerTestNGTestCase">
        <test-method signature="TestToPass()[pri:1, instance:listeners.ListenerTestNGTestCase@7ea9e1e2]" started-at="2024-01-04T01:34:20 IST" name="TestToPass" finished-at="2024-01-04T01:35:32 IST" duration-ms="72318" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestToPass -->
        <test-method signature="TestToSkip()[pri:2, instance:listeners.ListenerTestNGTestCase@7ea9e1e2]" started-at="2024-01-04T01:35:32 IST" name="TestToSkip" finished-at="2024-01-04T01:35:32 IST" duration-ms="4" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping - This is not ready for testing ]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping - This is not ready for testing 
at listeners.ListenerTestNGTestCase.TestToSkip(ListenerTestNGTestCase.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestToSkip -->
        <test-method signature="TestToFail()[pri:3, instance:listeners.ListenerTestNGTestCase@7ea9e1e2]" started-at="2024-01-04T01:35:32 IST" name="TestToFail" finished-at="2024-01-04T01:35:34 IST" duration-ms="1922" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestToFail -->
      </class> <!-- listeners.ListenerTestNGTestCase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
